#!/usr/bin/env node
// evidence.mjs: turn a `claude plugin eval` result into public-safe evidence bound to a commit.
//
// The raw aggregate-result.json cannot be committed as is: it holds absolute paths (the plugin's location on
// the machine that ran it) and model-written text (judge explanations, file contents) that this repository's
// scrub rules forbid. This writes a summary that keeps everything needed to check a claim (scores, every
// grader's pass or fail per run, deltas, versions, run settings, cost estimate) and the sha256 of the raw file,
// which stays on the machine that produced it.
//
//   node scripts/evidence.mjs <aggregate-result.json> [--sha <commit>] [--notes <file.md>] [--out <dir>]
//
// Writes evidence/<sha>/summary.json and evidence/<sha>/SUMMARY.md (or --out), then runs
// scripts/scrub-check.sh --path on the output and deletes it again if the scan fails. Exit 0 written,
// 2 refused (bad input, unknown commit, scrub failure).

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..");
const argv = process.argv.slice(2);
const opt = (k) => (argv.includes(k) ? argv[argv.indexOf(k) + 1] : null);
const refuse = (msg) => { console.error(`evidence: refused: ${msg}`); process.exit(2); };

const input = argv.find((a, i) => !a.startsWith("--") && !["--sha", "--notes", "--out"].includes(argv[i - 1]));
if (!input || !existsSync(input)) refuse("give the path to a claude plugin eval aggregate-result.json");
const rawBytes = readFileSync(input);
let raw;
try { raw = JSON.parse(rawBytes.toString("utf8")); } catch (e) { refuse(`not valid JSON: ${e.message}`); }
if (raw.schemaVersion !== 1 || !Array.isArray(raw.cases)) refuse(`unexpected format (schemaVersion ${raw.schemaVersion}); this writer knows schemaVersion 1`);

let sha = opt("--sha");
try { sha = execFileSync("git", ["-C", repo, "rev-parse", "--verify", `${sha ?? "HEAD"}^{commit}`], { stdio: ["ignore", "pipe", "ignore"] }).toString().trim(); }
catch { refuse(`commit ${sha ?? "HEAD"} is not in this repository`); }

const graderTypes = new Map();
for (const c of raw.cases) for (const g of c.graders ?? []) graderTypes.set(`${c.name}/${g.name}`, g.type);

const summarizeRun = (caseName, r) => ({
  score: r.score,
  passed: r.passed,
  turns: r.turns,
  error: r.error ? "error (see raw result)" : null,
  skippedPaidGraders: r.skippedPaidGraders,
  graders: (r.graders ?? []).map((g) => ({ name: g.name, type: graderTypes.get(`${caseName}/${g.name}`) ?? null, passed: g.passed, scored: g.scored !== false, votes: Array.isArray(g.judgeVotes) ? g.judgeVotes.map((v) => (v ? "PASS" : "FAIL")) : undefined })),
});

const summary = {
  kind: "skillgate eval evidence",
  schema: 1,
  commit: sha,
  rawResultSha256: createHash("sha256").update(rawBytes).digest("hex"),
  rawResultNote: "The raw aggregate-result.json holds machine paths and model-written text, so it is kept on the machine that ran it and identified here by its hash.",
  claudeVersion: raw.claudeVersion,
  startedAt: raw.startedAt,
  durationSeconds: raw.durationSeconds,
  costUsdListPriceEstimate: raw.costUsd,
  costNote: "List-price estimate reported by claude plugin eval for running the eval itself. Not plan usage, and not a savings figure.",
  partial: raw.partial,
  settings: { ablation: raw.suite?.ablation, threshold: raw.suite?.threshold, concurrency: raw.suite?.concurrency },
  plugins: (raw.suite?.plugins ?? []).map((p) => ({ name: p.name, version: p.version })),
  aggregates: raw.aggregates,
  cases: raw.cases.map((c) => ({
    name: c.name,
    runsPerCase: c.runsPerCase,
    maxTurns: c.maxTurns,
    score: c.aggregates?.score,
    delta: c.aggregates?.delta,
    arms: Object.fromEntries(Object.entries(c.arms ?? {}).map(([arm, runs]) => [arm, runs.map((r) => summarizeRun(c.name, r))])),
  })),
};

const fmt = (x) => (typeof x === "number" ? x.toFixed(2) : "n/a");
const lines = [];
lines.push(`# Eval evidence for ${sha.slice(0, 12)}`, "", "Kind: Reference. Generated by `scripts/evidence.mjs` from a `claude plugin eval` run; do not edit by hand.", "");
lines.push(`- Commit: \`${sha}\``);
lines.push(`- Plugins: ${summary.plugins.map((p) => `\`${p.name}\` ${p.version}`).join(", ") || "n/a"}`);
lines.push(`- Claude Code: ${summary.claudeVersion}; started ${summary.startedAt}; ${summary.durationSeconds} s; ablation ${summary.settings.ablation}; partial: ${summary.partial}`);
lines.push(`- Cost: about $${fmt(summary.costUsdListPriceEstimate)}, the eval tool's list-price estimate for running this eval (not plan usage, not a savings figure)`);
lines.push(`- Raw result sha256: \`${summary.rawResultSha256}\``, "");
lines.push(`Overall score with the plugin: ${fmt(summary.aggregates?.overallScore)}; mean difference with and without: ${fmt(summary.aggregates?.meanDelta)}.`, "");
lines.push("| Case | With plugin | Difference | Runs per arm |", "|---|---|---|---|");
for (const c of summary.cases) lines.push(`| \`${c.name}\` | ${fmt(c.score)} | ${fmt(c.delta)} | ${c.runsPerCase} |`);
lines.push("", "## Checks per case", "", "Counts are runs passed out of runs. Indicator checks (whether the skill fired) are shown but not scored.", "");
for (const c of summary.cases) {
  lines.push(`### \`${c.name}\``, "", "| Check | Type | With plugin | Without plugin |", "|---|---|---|---|");
  const names = [...new Set(Object.values(c.arms).flat().flatMap((r) => r.graders.map((g) => g.name)))];
  for (const n of names) {
    const count = (arm) => { const runs = c.arms[arm] ?? []; const hits = runs.map((r) => r.graders.find((g) => g.name === n)).filter(Boolean); return hits.length ? `${hits.filter((g) => g.passed).length} of ${hits.length}` : "not run"; };
    const g0 = Object.values(c.arms).flat().flatMap((r) => r.graders).find((g) => g.name === n);
    lines.push(`| ${n}${g0 && !g0.scored ? " (indicator)" : ""} | ${g0?.type ?? "n/a"} | ${count("with")} | ${count("without")} |`);
  }
  lines.push("");
}
const notesPath = opt("--notes");
if (notesPath) {
  if (!existsSync(notesPath)) refuse(`notes file ${notesPath} not found`);
  lines.push("## Notes", "", readFileSync(notesPath, "utf8").trim(), "");
}

const outDir = resolve(opt("--out") ?? join(repo, "evidence", sha));
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "summary.json"), JSON.stringify(summary, null, 2) + "\n");
writeFileSync(join(outDir, "SUMMARY.md"), lines.join("\n"));

let scanOut = "", scanCode = 0;
try { scanOut = execFileSync("bash", [join(here, "scrub-check.sh"), "--path", outDir], { stdio: ["ignore", "pipe", "pipe"] }).toString(); }
catch (e) { scanCode = e.status ?? 1; scanOut = `${e.stdout ?? ""}${e.stderr ?? ""}`; }
if (scanCode !== 0) {
  rmSync(join(outDir, "summary.json"), { force: true });
  rmSync(join(outDir, "SUMMARY.md"), { force: true });
  console.error(scanOut.trim());
  refuse(scanCode === 2 ? "the scrub check could not run in full (no denylist?), so nothing was written" : "the summary failed the scrub check, so nothing was written");
}
const shown = outDir.startsWith(repo + "/") ? outDir.slice(repo.length + 1) : outDir;
console.log(`wrote ${shown}/summary.json and SUMMARY.md (scrub check passed)`);
